USE [master]
GO

/****** Object:  Database [NotareTest]    Script Date: 09/15/2011 13:28:00 ******/
CREATE DATABASE [Notare] ON  PRIMARY 
( NAME = N'Notare_Data', FILENAME = N'D:\Programme\Microsoft SQL Server\MSSQL.1\MSSQL\Data\Notare.MDF' , SIZE = 5504KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Notare_Log', FILENAME = N'C:\Programme\Microsoft SQL Server\MSSQL.1\MSSQL\Data\Notare.LDF' , SIZE = 5696KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [Notare] SET COMPATIBILITY_LEVEL = 80
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Notare].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [Notare] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Notare] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Notare] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Notare] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Notare] SET ARITHABORT OFF 
GO

ALTER DATABASE [Notare] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Notare] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Notare] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Notare] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Notare] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Notare] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Notare] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Notare] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Notare] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Notare] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Notare] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Notare] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Notare] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Notare] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Notare] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Notare] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Notare] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Notare] SET  READ_WRITE 
GO

ALTER DATABASE [Notare] SET RECOVERY FULL 
GO

ALTER DATABASE [Notare] SET  MULTI_USER 
GO

ALTER DATABASE [Notare] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [Notare] SET DB_CHAINING OFF 
GO


